#!/usr/bin/env node
// sync-rules.mjs — bidirectional sync between .cursor/rules and .claude/rules + .claude/skills + CLAUDE.md.
//
// Usage:
//   node scripts/sync-rules.mjs              Smart bidirectional sync (mtime decides per file)
//   node scripts/sync-rules.mjs --from cursor   Force cursor → claude (overwrites claude side)
//   node scripts/sync-rules.mjs --from claude   Force claude → cursor (overwrites cursor side)
//   node scripts/sync-rules.mjs --check          Dry-run; print what would change, write nothing
//   node scripts/sync-rules.mjs --init           First-time migration (replaces cursor2claude CLAUDE.md)
//   node scripts/sync-rules.mjs --prune          Also delete orphaned generated files (off by default)
//   node scripts/sync-rules.mjs --verbose        Verbose logging
//
//   --check with --prune logs would-delete only; files stay on disk, so maps are not reloaded and
//   the per-slug loop may still print planned writes that a real --prune run would skip. Use --prune
//   without --check to validate deletion behavior.
//
// Mapping:
//   Cursor                                       <->  Claude
//   ─────────────────────────────────────────────────────────────────────────────
//   .cursor/rules/X.mdc  alwaysApply:true        <->  CLAUDE.md inline section "## X"
//   .cursor/rules/X.mdc  globs:<patterns>        <->  .claude/rules/X.md  paths:[<patterns>]
//   .cursor/rules/X.mdc  description-only        <->  .claude/skills/X/SKILL.md
//
// Excluded from mirroring (maintained separately per editor; see EXCLUDED_SYNC_SLUGS in this file).
//
// Generated files (one side written from the other) get a "<!-- generated-from: ... -->" marker
// so a future sync knows the source. If you edit a generated file, its mtime advances and the
// next sync will treat THAT side as the new source.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ────────────────────────────────────────────────────────────────────────────
// Paths and constants
// ────────────────────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), "..");

const CURSOR_DIR = path.join(ROOT, ".cursor", "rules");
const CLAUDE_RULES_DIR = path.join(ROOT, ".claude", "rules");
const CLAUDE_SKILLS_DIR = path.join(ROOT, ".claude", "skills");
const CLAUDE_MD = path.join(ROOT, "CLAUDE.md");

const ALWAYS_START = "<!-- ALWAYS-APPLY-START — managed by scripts/sync-rules.mjs — DO NOT EDIT INSIDE THIS BLOCK MANUALLY -->";
const ALWAYS_END = "<!-- ALWAYS-APPLY-END — your custom CLAUDE.md content goes ABOVE this block -->";

const SCRIPT_NAME = "scripts/sync-rules.mjs";

const GENERATED_HEADER = (sourceRel) =>
  `<!-- generated-from: ${sourceRel} — DO NOT EDIT THIS FILE; edit the source instead. Managed by ${SCRIPT_NAME}. -->`;
const GENERATED_REGEX = /<!--\s*generated-from:\s*(\S+)\s*—.*?-->/;

// Per-rule HTML markers used inside the CLAUDE.md always-apply block. Using
// markers (instead of `## NAME` headings) means rule BODIES can freely contain
// their own `##` subheadings without confusing the parser.
const RULE_BLOCK_START = (slug) => `<!-- rule:${slug} -->`;
const RULE_BLOCK_END = (slug) => `<!-- /rule:${slug} -->`;
const RULE_BLOCK_RE = /<!--\s*rule:([\w.-]+)\s*-->\s*\n?([\s\S]*?)\n?<!--\s*\/rule:\1\s*-->/g;

/** Provider-specific “how to run sync” rules — not mirrored; each side is edited manually. */
const EXCLUDED_SYNC_SLUGS = new Set(["sync-rules-on-edit"]);

function isExcludedSyncSlug(slug) {
  return EXCLUDED_SYNC_SLUGS.has(slug);
}

// ────────────────────────────────────────────────────────────────────────────
// Args
// ────────────────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const flags = { from: null, check: false, verbose: false, init: false, prune: false };
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === "--from") flags.from = args[++i];
  else if (a === "--check") flags.check = true;
  else if (a === "--verbose" || a === "-v") flags.verbose = true;
  else if (a === "--init") flags.init = true;
  else if (a === "--prune") flags.prune = true;
  else if (a === "--help" || a === "-h") {
    console.log(fs.readFileSync(__filename, "utf8").split("\n").slice(1, 22).map(l => l.replace(/^\/\/ ?/, "")).join("\n"));
    process.exit(0);
  } else {
    console.error(`Unknown flag: ${a}`);
    process.exit(2);
  }
}

if (flags.from && !["cursor", "claude"].includes(flags.from)) {
  console.error(`--from must be "cursor" or "claude"`);
  process.exit(2);
}

// ────────────────────────────────────────────────────────────────────────────
// Tiny YAML frontmatter parser/writer (handles only what Cursor + Claude rules use)
// ────────────────────────────────────────────────────────────────────────────

function parseFrontmatter(content) {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: content.trimStart() };
  const fm = {};
  let currentArrayKey = null;
  for (const raw of m[1].split(/\r?\n/)) {
    const line = raw.replace(/\r$/, "");
    if (!line.trim()) { currentArrayKey = null; continue; }
    // multi-line array continuation: "  - value"
    const arrMatch = line.match(/^\s+-\s+(.*)$/);
    if (arrMatch && currentArrayKey) {
      fm[currentArrayKey].push(unquote(arrMatch[1].trim()));
      continue;
    }
    // key: value
    const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$/);
    if (!kvMatch) { currentArrayKey = null; continue; }
    const key = kvMatch[1];
    const rawValue = kvMatch[2];
    if (rawValue === "") {
      // value follows on next lines as an array
      fm[key] = [];
      currentArrayKey = key;
    } else if (rawValue === "true") {
      fm[key] = true;
      currentArrayKey = null;
    } else if (rawValue === "false") {
      fm[key] = false;
      currentArrayKey = null;
    } else if (rawValue.startsWith("[") && rawValue.endsWith("]")) {
      fm[key] = rawValue.slice(1, -1).split(",").map(s => unquote(s.trim())).filter(Boolean);
      currentArrayKey = null;
    } else if (rawValue === ">" || rawValue === "|") {
      // YAML block scalar — collect indented continuation lines
      // (rare in our rules; collapse to single string)
      fm[key] = "";
      currentArrayKey = null;
      // we don't aggressively collect block scalars; downstream code handles strings well enough
    } else {
      fm[key] = unquote(rawValue);
      currentArrayKey = null;
    }
  }
  return { fm, body: m[2].trimStart() };
}

function unquote(s) {
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1);
  }
  return s;
}

function writeFrontmatter(fm, body) {
  const lines = ["---"];
  for (const [k, v] of Object.entries(fm)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      lines.push(`${k}:`);
      for (const item of v) lines.push(`  - ${quoteIfNeeded(item)}`);
    } else if (typeof v === "boolean") {
      lines.push(`${k}: ${v}`);
    } else {
      lines.push(`${k}: ${quoteIfNeeded(String(v))}`);
    }
  }
  lines.push("---", "", body.trimEnd(), "");
  return lines.join("\n");
}

function quoteIfNeeded(s) {
  if (/^[\w\-./*?@:!,\s+=]+$/.test(s) && !/^(true|false|null|yes|no|on|off)$/i.test(s)) {
    return s;
  }
  return JSON.stringify(s);
}

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

const log = (...a) => console.log(...a);
const vlog = (...a) => { if (flags.verbose) console.log(...a); };

function ensureDir(p) {
  if (!flags.check) fs.mkdirSync(p, { recursive: true });
}

function readFileSafe(p) {
  try { return fs.readFileSync(p, "utf8"); } catch { return null; }
}

function writeFileIfChanged(p, content) {
  const existing = readFileSafe(p);
  if (existing === content) return false;
  // Semantic equality: prevents bidirectional ping-pong when only a generated
  // header differs but the underlying rule (frontmatter + body) is the same.
  if (isSemanticallyEqual(existing, content)) return false;
  if (flags.check) {
    log(`  [DRY] would write: ${path.relative(ROOT, p)}`);
    return true;
  }
  ensureDir(path.dirname(p));
  fs.writeFileSync(p, content);
  return true;
}

function deepEqual(a, b) {
  if (a === b) return true;
  if (typeof a !== typeof b) return false;
  if (a == null || b == null) return false;
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    return a.every((v, i) => deepEqual(v, b[i]));
  }
  if (typeof a === "object") {
    const ak = Object.keys(a).sort();
    const bk = Object.keys(b).sort();
    if (ak.length !== bk.length) return false;
    return ak.every((k, i) => k === bk[i] && deepEqual(a[k], b[k]));
  }
  return false;
}

function normalizeFmForCompare(fm) {
  const out = {};
  for (const [k, v] of Object.entries(fm)) {
    if (v === undefined || v === null) continue;
    if (k === "globs" || k === "paths") {
      const arr = normalizeGlobs(v).slice().sort();
      if (arr.length === 0) continue;
      out[k] = arr;
    } else if (typeof v === "string") {
      const t = v.trim();
      if (t.length === 0) continue;
      out[k] = t;
    } else {
      out[k] = v;
    }
  }
  return out;
}

function isSemanticallyEqual(existing, candidate) {
  if (existing == null) return false;
  if (existing === candidate) return true;
  let e, n;
  try {
    e = parseFrontmatter(existing);
    n = parseFrontmatter(candidate);
  } catch {
    return false;
  }
  if (!deepEqual(normalizeFmForCompare(e.fm), normalizeFmForCompare(n.fm))) return false;
  const eBody = stripGeneratedHeader(e.body).trim();
  const nBody = stripGeneratedHeader(n.body).trim();
  return eBody === nBody;
}

function deleteFile(p, why) {
  if (!fs.existsSync(p)) return false;
  if (flags.check) {
    log(`  [DRY] would delete: ${path.relative(ROOT, p)} (${why})`);
    return true;
  }
  fs.unlinkSync(p);
  return true;
}

function mtimeOf(p) {
  try { return fs.statSync(p).mtimeMs; } catch { return 0; }
}

function rel(p) { return path.relative(ROOT, p); }

function normalizeGlobs(g) {
  if (!g) return [];
  if (Array.isArray(g)) return g.filter(Boolean);
  return String(g).split(",").map(s => s.trim()).filter(Boolean);
}

function classifyCursor(fm) {
  if (fm.alwaysApply === true) return "always";
  if (normalizeGlobs(fm.globs).length > 0) return "paths";
  if (fm.description) return "skill";
  return "always"; // no frontmatter or only legacy: treat as always-apply
}

// ────────────────────────────────────────────────────────────────────────────
// Cursor → Claude conversions
// ────────────────────────────────────────────────────────────────────────────

function cursorToClaudeRule(cursorPath, fm, body) {
  const slug = path.basename(cursorPath, ".mdc");
  const claudeFm = { paths: normalizeGlobs(fm.globs) };
  if (fm.description) claudeFm.description = fm.description;
  const header = GENERATED_HEADER(rel(cursorPath));
  const cleanBody = stripGeneratedHeader(body);
  const content = writeFrontmatter(claudeFm, `${header}\n\n${cleanBody}`);
  return { target: path.join(CLAUDE_RULES_DIR, `${slug}.md`), content };
}

function cursorToClaudeSkill(cursorPath, fm, body) {
  const slug = path.basename(cursorPath, ".mdc");
  const description = fm.description
    ? `${fm.description}\n  Trigger: ${fm.description}`
    : `Project rule from ${slug}.\n  Trigger: When working on ${slug}-related tasks.`;
  const flatFm = {
    name: slug,
    description,
    license: "Apache-2.0",
  };
  const header = GENERATED_HEADER(rel(cursorPath));
  const cleanBody = stripGeneratedHeader(body);
  const content = writeFrontmatter(flatFm, `${header}\n\n${cleanBody}`);
  return { target: path.join(CLAUDE_SKILLS_DIR, slug, "SKILL.md"), content };
}

// ────────────────────────────────────────────────────────────────────────────
// Claude → Cursor conversions
// ────────────────────────────────────────────────────────────────────────────

function claudeRuleToCursor(claudePath, fm, body) {
  const slug = path.basename(claudePath, ".md");
  const cursorFm = {};
  if (fm.description) cursorFm.description = fm.description;
  const paths = Array.isArray(fm.paths) ? fm.paths : normalizeGlobs(fm.paths);
  if (paths.length > 0) cursorFm.globs = paths.length === 1 ? paths[0] : paths;
  cursorFm.alwaysApply = false;
  const header = GENERATED_HEADER(rel(claudePath));
  // Strip any prior generated-from header from the body before re-emitting
  const cleanBody = stripGeneratedHeader(body);
  const content = writeFrontmatter(cursorFm, `${header}\n\n${cleanBody}`);
  return { target: path.join(CURSOR_DIR, `${slug}.mdc`), content };
}

function claudeSkillToCursor(skillPath, fm, body) {
  const slug = path.basename(path.dirname(skillPath));
  const description = stripTrigger(fm.description || "");
  const cursorFm = { description, alwaysApply: false };
  const header = GENERATED_HEADER(rel(skillPath));
  const cleanBody = stripGeneratedHeader(body);
  const content = writeFrontmatter(cursorFm, `${header}\n\n${cleanBody}`);
  return { target: path.join(CURSOR_DIR, `${slug}.mdc`), content };
}

function stripTrigger(s) {
  // "  Trigger: foo." line, multi-line description: keep only first sentence
  return String(s).split(/\n\s*Trigger:/)[0].trim();
}

function stripGeneratedHeader(body) {
  return body.replace(/^<!--\s*generated-from:[\s\S]*?-->\s*\n?/, "");
}

// ────────────────────────────────────────────────────────────────────────────
// CLAUDE.md inline always-apply section
// ────────────────────────────────────────────────────────────────────────────

function readClaudeMdSections() {
  const content = readFileSafe(CLAUDE_MD) || "";
  const startIdx = content.indexOf(ALWAYS_START);
  const endIdx = content.indexOf(ALWAYS_END);
  if (startIdx === -1 || endIdx === -1) {
    return { sections: new Map(), preserved: content, hasBlock: false };
  }
  const block = content.slice(startIdx + ALWAYS_START.length, endIdx);
  const preserved = (content.slice(0, startIdx) + content.slice(endIdx + ALWAYS_END.length)).trim();
  // Each rule is wrapped in <!-- rule:slug --> ... <!-- /rule:slug --> markers.
  // Rule bodies may freely contain `##` headings — markers disambiguate.
  const sections = new Map();
  RULE_BLOCK_RE.lastIndex = 0;
  let m;
  while ((m = RULE_BLOCK_RE.exec(block)) !== null) {
    sections.set(m[1], m[2].trim());
  }
  return { sections, preserved, hasBlock: true };
}

function writeClaudeMdWithAlwaysSections(alwaysMap /* Map<slug, body> */, preserved) {
  const blockLines = [];
  const sortedSlugs = [...alwaysMap.keys()].sort();
  for (const slug of sortedSlugs) {
    blockLines.push(
      `## ${slug}`,
      "",
      RULE_BLOCK_START(slug),
      alwaysMap.get(slug).trim(),
      RULE_BLOCK_END(slug),
      "",
    );
  }
  const block = blockLines.join("\n").trimEnd();
  const userPart = preserved && preserved.trim().length > 0 ? `${preserved.trim()}\n\n` : "";
  const out = `${userPart}${ALWAYS_START}\n\n${block}\n\n${ALWAYS_END}\n`;
  return writeFileIfChanged(CLAUDE_MD, out);
}

// ────────────────────────────────────────────────────────────────────────────
// Discovery
// ────────────────────────────────────────────────────────────────────────────

function listFiles(dir, ext) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith(ext)).map(f => path.join(dir, f));
}

function listSkills() {
  if (!fs.existsSync(CLAUDE_SKILLS_DIR)) return [];
  return fs.readdirSync(CLAUDE_SKILLS_DIR)
    .map(d => path.join(CLAUDE_SKILLS_DIR, d, "SKILL.md"))
    .filter(p => fs.existsSync(p));
}

// ────────────────────────────────────────────────────────────────────────────
// Build per-slug "rule view" from each side, resolve direction per slug
// ────────────────────────────────────────────────────────────────────────────

function loadCursorRules() {
  const out = new Map(); // slug → { kind, mtime, fm, body, sourcePath }
  for (const p of listFiles(CURSOR_DIR, ".mdc")) {
    const slug = path.basename(p, ".mdc");
    if (isExcludedSyncSlug(slug)) continue;
    const content = readFileSafe(p) || "";
    const { fm, body } = parseFrontmatter(content);
    const kind = classifyCursor(fm);
    out.set(slug, { kind, mtime: mtimeOf(p), fm, body, sourcePath: p });
  }
  return out;
}

function loadClaudeRules() {
  const out = new Map(); // slug → { kind: 'paths'|'skill'|'always', mtime, fm, body, sourcePath }
  for (const p of listFiles(CLAUDE_RULES_DIR, ".md")) {
    const slug = path.basename(p, ".md");
    if (isExcludedSyncSlug(slug)) continue;
    const content = readFileSafe(p) || "";
    const { fm, body } = parseFrontmatter(content);
    out.set(slug, { kind: "paths", mtime: mtimeOf(p), fm, body, sourcePath: p });
  }
  for (const p of listSkills()) {
    const slug = path.basename(path.dirname(p));
    if (isExcludedSyncSlug(slug)) continue;
    const content = readFileSafe(p) || "";
    const { fm, body } = parseFrontmatter(content);
    if (out.has(slug)) {
      console.warn(`[warn] ${slug} exists as both .claude/rules and .claude/skills — skipping skill`);
      continue;
    }
    out.set(slug, { kind: "skill", mtime: mtimeOf(p), fm, body, sourcePath: p });
  }
  // Always-apply sections from CLAUDE.md
  const { sections } = readClaudeMdSections();
  for (const [slug, body] of sections) {
    if (isExcludedSyncSlug(slug)) continue;
    if (out.has(slug)) {
      console.warn(`[warn] ${slug} is in CLAUDE.md AND .claude/rules/skills — CLAUDE.md wins for always-apply mode`);
    }
    out.set(slug, { kind: "always", mtime: mtimeOf(CLAUDE_MD), fm: { alwaysApply: true }, body, sourcePath: CLAUDE_MD });
  }
  return out;
}

// ────────────────────────────────────────────────────────────────────────────
// Sync engine
// ────────────────────────────────────────────────────────────────────────────

function syncCursorToClaude(slug, cursorEntry, claudeMd /* mutable Map */, stats) {
  const { kind, fm, body, sourcePath } = cursorEntry;
  if (kind === "always") {
    claudeMd.set(slug, body);
    stats.alwaysUpdated.add(slug);
    vlog(`  ✓ ${slug} → CLAUDE.md (always-apply)`);
    return;
  }
  if (kind === "paths") {
    const { target, content } = cursorToClaudeRule(sourcePath, fm, body);
    if (writeFileIfChanged(target, content)) {
      log(`  ✓ ${rel(sourcePath)} → ${rel(target)}`);
      stats.written++;
    } else vlog(`  ⊘ ${slug} unchanged (paths)`);
    return;
  }
  if (kind === "skill") {
    const { target, content } = cursorToClaudeSkill(sourcePath, fm, body);
    if (writeFileIfChanged(target, content)) {
      log(`  ✓ ${rel(sourcePath)} → ${rel(target)}`);
      stats.written++;
    } else vlog(`  ⊘ ${slug} unchanged (skill)`);
    return;
  }
}

function syncClaudeToCursor(slug, claudeEntry, alwaysFromCursor /* Map */, stats) {
  const { kind, fm, body, sourcePath } = claudeEntry;
  if (kind === "always") {
    // Build a Cursor rule with alwaysApply: true.
    // Preserve the existing cursor file's description (if any) — CLAUDE.md
    // does not round-trip frontmatter, so without preservation each sync would
    // overwrite it with a synthetic value, causing useless rewrites.
    const target = path.join(CURSOR_DIR, `${slug}.mdc`);
    const cursorFm = { alwaysApply: true };
    const existingContent = readFileSafe(target);
    if (existingContent) {
      const { fm: existingFm } = parseFrontmatter(existingContent);
      if (existingFm.description) cursorFm.description = existingFm.description;
    }
    const header = GENERATED_HEADER(rel(CLAUDE_MD));
    const content = writeFrontmatter(cursorFm, `${header}\n\n${body}`);
    if (writeFileIfChanged(target, content)) {
      log(`  ✓ CLAUDE.md#${slug} → ${rel(target)}`);
      stats.written++;
    } else vlog(`  ⊘ ${slug} unchanged (always)`);
    return;
  }
  if (kind === "paths") {
    const { target, content } = claudeRuleToCursor(sourcePath, fm, body);
    if (writeFileIfChanged(target, content)) {
      log(`  ✓ ${rel(sourcePath)} → ${rel(target)}`);
      stats.written++;
    } else vlog(`  ⊘ ${slug} unchanged (paths)`);
    return;
  }
  if (kind === "skill") {
    const { target, content } = claudeSkillToCursor(sourcePath, fm, body);
    if (writeFileIfChanged(target, content)) {
      log(`  ✓ ${rel(sourcePath)} → ${rel(target)}`);
      stats.written++;
    } else vlog(`  ⊘ ${slug} unchanged (skill)`);
    return;
  }
}

function decideDirection(cursorEntry, claudeEntry) {
  if (cursorEntry && !claudeEntry) return "cursor";
  if (claudeEntry && !cursorEntry) return "claude";
  // Both exist — newer mtime wins
  if (cursorEntry.mtime > claudeEntry.mtime) return "cursor";
  if (claudeEntry.mtime > cursorEntry.mtime) return "claude";
  // Tie — prefer cursor (deterministic; sync is idempotent so no rewrite if content matches)
  return "cursor";
}

function pruneOrphans(cursorMap, claudeMap, stats) {
  // Generated files whose source no longer exists → delete (only with --prune)
  if (!flags.prune) return;
  // .claude/rules — generated from cursor
  for (const p of listFiles(CLAUDE_RULES_DIR, ".md")) {
    const slug = path.basename(p, ".md");
    if (isExcludedSyncSlug(slug)) continue;
    if (!cursorMap.has(slug)) {
      const content = readFileSafe(p) || "";
      const m = content.match(GENERATED_REGEX);
      if (m) {
        if (deleteFile(p, `orphan generated from missing ${m[1]}`)) {
          log(`  ✗ pruned ${rel(p)}`);
          stats.deleted++;
        }
      }
    }
  }
  // .claude/skills — generated from cursor
  for (const p of listSkills()) {
    const slug = path.basename(path.dirname(p));
    if (isExcludedSyncSlug(slug)) continue;
    if (!cursorMap.has(slug)) {
      const content = readFileSafe(p) || "";
      const m = content.match(GENERATED_REGEX);
      if (m) {
        if (deleteFile(p, `orphan generated from missing ${m[1]}`)) {
          // remove empty skill dir
          try { fs.rmdirSync(path.dirname(p)); } catch {}
          log(`  ✗ pruned ${rel(p)}`);
          stats.deleted++;
        }
      }
    }
  }
  // .cursor/rules — generated from claude
  for (const p of listFiles(CURSOR_DIR, ".mdc")) {
    const slug = path.basename(p, ".mdc");
    if (isExcludedSyncSlug(slug)) continue;
    if (!claudeMap.has(slug)) {
      const content = readFileSafe(p) || "";
      const m = content.match(GENERATED_REGEX);
      if (m) {
        if (deleteFile(p, `orphan generated from missing ${m[1]}`)) {
          log(`  ✗ pruned ${rel(p)}`);
          stats.deleted++;
        }
      }
    }
  }
}

function migrateCursor2Claude() {
  // Detect cursor2claude legacy CLAUDE.md ("⚙️ Auto-generated by cursor2claude") and clear it
  const content = readFileSafe(CLAUDE_MD) || "";
  if (!content.includes("Auto-generated by cursor2claude")) return false;
  log("[init] Detected legacy cursor2claude CLAUDE.md — preserving Project Notes section.");
  // Try to preserve content below "DO NOT EDIT ABOVE THIS LINE"
  const splitIdx = content.indexOf("DO NOT EDIT ABOVE THIS LINE");
  let userContent = "";
  if (splitIdx !== -1) {
    const after = content.slice(splitIdx).split("\n").slice(1).join("\n");
    userContent = after.trim();
  }
  if (!flags.check) {
    fs.writeFileSync(CLAUDE_MD, `${ALWAYS_START}\n\n${ALWAYS_END}\n\n${userContent}\n`);
  } else {
    log(`  [DRY] would rewrite CLAUDE.md preserving user notes`);
  }
  return true;
}

// ────────────────────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────────────────────

function main() {
  log(`[sync-rules] mode: ${flags.from ? `force --from ${flags.from}` : "smart bidirectional"}${flags.check ? " (dry-run)" : ""}`);

  if (flags.init) migrateCursor2Claude();

  // Make sure target dirs exist (for first-time runs)
  ensureDir(CURSOR_DIR);
  ensureDir(CLAUDE_RULES_DIR);
  ensureDir(CLAUDE_SKILLS_DIR);

  let cursorMap = loadCursorRules();
  let claudeMap = loadClaudeRules();

  const stats = { written: 0, deleted: 0, alwaysUpdated: new Set(), conflicts: 0 };

  // Prune BEFORE syncing so that deletions on one side propagate to the other.
  // Otherwise a missing cursor file would be regenerated from claude before
  // the prune could remove the claude orphan, leaving deletion intent lost.
  // One pass is enough: the sync loop only copies between existing slugs and does not introduce new
  // generated orphans, so no post-loop prune is needed.
  pruneOrphans(cursorMap, claudeMap, stats);
  if (flags.prune && !flags.check) {
    cursorMap = loadCursorRules();
    claudeMap = loadClaudeRules();
  }
  const allSlugs = new Set([...cursorMap.keys(), ...claudeMap.keys()]);

  // We accumulate always-apply slugs to (re)write CLAUDE.md once at the end.
  // Start from the current CLAUDE.md state, then mutate based on cursor side.
  const { sections: currentAlwaysSections, preserved } = readClaudeMdSections();
  const alwaysMap = new Map(currentAlwaysSections);

  for (const slug of allSlugs) {
    const c = cursorMap.get(slug);
    const k = claudeMap.get(slug);

    let direction;
    if (flags.from === "cursor") direction = c ? "cursor" : "claude";
    else if (flags.from === "claude") direction = k ? "claude" : "cursor";
    else direction = decideDirection(c, k);

    if (direction === "cursor") {
      if (!c) { vlog(`  ⊘ ${slug} skipped (no cursor source)`); continue; }
      syncCursorToClaude(slug, c, alwaysMap, stats);
      // If kind was always, we updated alwaysMap; if it changed away from always, drop from CLAUDE.md
      if (c.kind !== "always" && alwaysMap.has(slug)) alwaysMap.delete(slug);
    } else {
      if (!k) { vlog(`  ⊘ ${slug} skipped (no claude source)`); continue; }
      syncClaudeToCursor(slug, k, alwaysMap, stats);
      if (k.kind === "always") alwaysMap.set(slug, k.body);
      else if (alwaysMap.has(slug)) alwaysMap.delete(slug);
    }
  }

  // Rewrite CLAUDE.md if always-apply set changed
  const beforeKeys = JSON.stringify([...currentAlwaysSections.keys()].sort());
  const afterKeys = JSON.stringify([...alwaysMap.keys()].sort());
  const alwaysChanged = beforeKeys !== afterKeys ||
    [...alwaysMap.entries()].some(([k, v]) => currentAlwaysSections.get(k) !== v);
  if (alwaysChanged || flags.init) {
    if (writeClaudeMdWithAlwaysSections(alwaysMap, preserved)) {
      log(`  ✓ CLAUDE.md rewrote always-apply section (${alwaysMap.size} rules)`);
      stats.written++;
    }
  }

  log(`[sync-rules] done — ${stats.written} written, ${stats.deleted} deleted${flags.check ? " (dry-run, nothing actually changed)" : ""}`);
}

try {
  main();
} catch (err) {
  console.error(`[sync-rules] error: ${err.message}`);
  if (flags.verbose) console.error(err.stack);
  process.exit(1);
}
